# Site settings
title: Eureka College at 160
email: web@eureka.edu
description: "This Week in Eureka College History commemorates the 160th anniversary of the founding of Eureka College on February 6, 1855, and is scheduled to run weekly through February 6, 2016."
baseurl: "/160/blog" # the subpath of your site, e.g. /blog/
url: "http://www.eureka.edu" # the base hostname & protocol for your site
twitter_username: eurekacollege

# Build settings
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /articles/:title
paginate: 4
